const l = {
  common: {
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save Changes',
    loading: 'Loading...',
    adding: 'Adding...',
    creating: 'Creating Account...',
    loggingIn: 'Logging In...',
    sending: 'Sending...',
    deleting: 'Deleting...',
    backToHome: 'Back to Home',
    backToLogin: 'Back to Log in',
    rememberedIt: 'Remembered it?',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    description: 'Description',
    signIn: 'Sign in',
    signUp: 'Sign up',
    getStarted: 'Get Started',
    logIn: 'Log in',
    logOut: 'Log out',
    signUpNow: 'Sign Up Now',
    signUpWithGoogle: 'Sign up with Google',
    search: 'Search',
    searchCars: 'Search Cars',
    loadMore: 'Load more',
    allCarsLoaded: 'All cars loaded',
    details: 'Details',
    specs: 'Specs',
    bookNow: 'Book Now',
    howItWorks: 'How it works',
    confirmReservation: 'Confirm Reservation',
    bookingFailed: 'Booking failed, please sign in to continue.',
    signInToReserve: 'Sign in to complete your reservation',
    noPhoto: 'No photo',
    pricePerDay: 'Price Per Day (€)',
    pickUp: 'Pick Up',
    returnDate: 'Return',
    estimatedTotal: 'Estimated Total',
    total: 'Total',
    unavailable: 'Unavailable',
    close: '✕',
    fileSelected: (n: number) => `${n} file selected`,
    filesSelected: (n: number) => `${n} files selected`,
    clickToUpload: 'Click to upload photos',
    days: (n: number) => `${n} day${n !== 1 ? 's' : ''}`,
    profileInitial: 'U',
    perDay: '/ day',
    andMore: (n: number) => `and ${n} more...`,
    saving: 'Saving...',
  },

  auth: {
    joinUs: 'Join Us',
    welcomeBack: 'Welcome Back',
    logInToRentMyCar: 'Log in to RentMyCar',
    createAnAccount: 'Create an Account',
    enterDetails: 'Enter your details to access your ride',
    startJourney: 'Start your journey with us today',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    forgotPassword: 'Forgot Password?',
    forgotPasswordHeading: 'Forgot your password?',
    forgotPasswordDesc: "Enter your email and we'll send you a reset link.",
    emailRequired: 'Email is required',
    enterEmail: 'Enter your email',
    sendResetLink: 'Send reset link',
    passwordResetSuccess:
      'Password reset link has been successfully sent to your email.',
    resetPasswordHeading: 'Reset your password',
    resetPasswordDesc: 'Enter and confirm your new password.',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordRequired: 'Password is required',
    confirmPasswordRequired: 'Please confirm your password',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordMaxLength: 'Password must be at most 128 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    invalidResetLink: 'This password reset link is invalid or missing.',
    resetPassword: 'Reset password',
    resettingPassword: 'Resetting password...',
    passwordResetComplete: 'Your password has been reset successfully.',
    somethingWrong: 'Something went wrong. Please try again.',
    createAccount: 'Create Account',
    errorOccurred: 'An error occurred. Please try again.',
    verifyEmailHeading: 'Verify your email',
    verificationSent:
      'We sent a verification link to your email. Please check your inbox and click the link to verify your account.',
    checkYourInbox:
      'Please check your inbox and click the verification link to verify your email address.',
    verificationSuccess: 'Your email has been verified successfully!',
    verificationFailed:
      'Verification failed. The link may be invalid or expired.',
    verifyButton: 'Verify Email',
    verifying: 'Verifying...',
    backToLogin: 'Back to Login',
    invalidCredentials: 'Invalid email or password',
    emailNotVerified: 'Please verify your email before logging in.',
  },

  cars: {
    addCar: 'Add Car',
    addNewCar: 'Add a New Car',
    addNewCarBtn: '+ Add New Car',
    myCars: 'My Cars',
    myRentals: 'My Rentals',
    addVehicleDesc: 'Add your vehicle details to create a rental listing',
    backToMyCars: 'Back to My Cars',
    secureListing: 'Secure listing setup',
    vehicleDetails: 'Vehicle details',
    vehicleDetailsDesc: 'Tell renters what makes your car the right choice.',
    rentalDetails: 'Location and pricing',
    rentalDetailsDesc: 'Set the pickup point and your daily rental price.',
    descriptionPlaceholder:
      'Describe the condition, features, and anything renters should know...',
    carImagesDesc: 'Add clear photos from several angles.',
    imageHint: 'JPG, PNG or WEBP',
    selectedPhotos: 'Selected photos',
    carImagePreview: 'Selected car preview',
    removeImage: 'Remove image',
    publishHint:
      'Review the details and publish your car when everything looks right.',
    publishCar: 'Publish Car',
    make: 'Make',
    model: 'Model',
    carType: 'Car Type',
    engineType: 'Engine Type',
    horsepower: 'Horsepower (HP)',
    horsepowerMobile: 'Horsepower',
    avgConsumption: 'Avg. Consumption',
    city: 'City',
    carLocation: 'Car Location',
    firstRegistration: 'First Registration',
    selectDate: 'Select date',
    pricePerDayLabel: 'Price Per Day (€)',
    carImages: 'Car Images',
    updateCar: 'Update Car',
    editVehicleDesc: 'Edit your vehicle details',
    saveChanges: 'Save Changes',
    deleteCar: 'Delete Car',
    deleteCarConfirm:
      'Are you sure you want to delete this car? This action cannot be undone.',
    deleteCarError: 'Failed to delete car. Please try again.',
    updateCarError: 'Failed to update car',
    firstRegistrationRequired: 'First registration is required!',
    atLeastOneImage: 'At least one image is required!',
    failedAddCar: 'Failed to add car. Please try again.',
    eg: 'e.g.',
    egCClass: 'e.g. C-Class',
    eg150: 'e.g. 150',
    eg65L: 'e.g. 6.5 L/100km',
    egLiman: 'e.g. Liman 3',
    eg45: 'e.g. 45',
    chooseFiles: 'Choose Files',
    carUnavailable: '🚗 Car unavailable',
  },

  search: {
    location: 'Location',
    allCities: 'All Cities (Serbia)',
    allCitiesMobile: 'All cities (Serbia)',
    pickUp: 'Pick Up',
    returnDate: 'Return',
    filters: 'Filters',
    priceRange: 'Price Range (per day)',
    priceRangeEur: 'Price Range (€/day)',
    priceRangePerDay: 'Price Range (per day)',
    min: 'Min',
    max: 'Max',
    minPlaceholder: 'Min',
    maxPlaceholder: 'Max',
    pickUpLabel: 'Pick Up',
    returnLabel: 'Return',
    carMake: 'Car Make',
    allMakes: 'All Makes',
    allManufacturers: 'All Manufacturers',
    carType: 'Car Type',
    allTypes: 'All Types',
    engineType: 'Engine Type',
    allEngineTypes: 'All Engine Types',
    pricesDisclaimer:
      'Prices in Euros (€) and exclude customized dropoff charges.',
    availableCars: 'Available Cars',
    noCarsFound: 'No cars found...',
    findPerfectRide: 'Find Your Perfect Ride',
    findCompareChoose:
      'Find, compare, and choose the perfect car for your next trip.',
    bookingForDays: (n: number) => `Booking for ${n} days`,
    pickUpDate: 'Pick-up Date',
    returnDateLabel: 'Return Date',
    selectDatesFirst:
      'Select pick-up and return dates to search for available cars.',
    searchFailed: 'We could not load available cars. Please try again.',
    startSearchTitle: 'Choose your dates to start searching',
    startSearchDescription:
      'Available cars will appear here after you select your trip dates.',
    carsFound: (n: number) => `${n} ${n === 1 ? 'car' : 'cars'} available`,
    showFilters: 'Show filters',
    hideFilters: 'Hide filters',
    clearFilters: 'Clear filters',
    tryDifferentSearch: 'Try different dates, another city, or fewer filters.',
  },

  booking: {
    bookMakeModel: (make: string, model: string) => `Book ${make} ${model}`,
    bookingSuccessful: 'Booking successful',
    errorCreatingBooking: 'Error creating booking',
    unauthorized: 'Unauthorized',
    missingRequiredFields: 'Missing required fields',
    carNotFound: 'Car not found',
    userNotFoundSession: 'User ID not found in session',
    cancelReservation: 'Cancel Reservation',
    cancelReservationConfirm:
      'Are you sure you want to cancel this reservation? The car will become available again for these dates.',
    keepReservation: 'Keep Reservation',
    cancellingReservation: 'Cancelling...',
    reservationCancelled: 'Reservation cancelled successfully',
    reservationAlreadyCancelled: 'This reservation is already cancelled',
    cannotCancelReservation:
      'You are not authorized to cancel this reservation',
  },

  profile: {
    editProfile: 'Edit Profile',
    editProfileBtn: 'Edit Profile',
    myCars: 'My Cars',
    myRentals: 'My Rentals',
    myCarsHeading: 'My Cars',
    myRentalsHeading: 'My Rentals',
    addNewCar: 'Add New Car',
    noCarsListed: "You haven't listed any cars yet.",
    noRentalsYet: "You haven't rented any cars yet.",
    memberSince: (date: string) => `Member since ${date}`,
    noPhoneNumber: 'No phone number added',
    cars: 'Cars',
    rentals: 'Rentals',
    rating: 'Rating',
    carOwner: 'Car owner',
    ownerProfile: 'Owner profile',
    ownerIntro: 'Meet the local owner behind the car you are considering.',
    contactOwner: 'Contact this owner',
    contactDescription:
      'Use the details below when you need to coordinate your rental directly with the owner.',
    emailAddress: 'Email address',
    phoneNumber: 'Phone number',
    member: 'Member',
    rentMyCarOwner: 'RentMyCar owner',
    noRatingYet: 'New',
    viewOwnerProfile: 'View public profile',
    ownerAtGlance: 'Owner at a glance',
    carsListed: 'Cars listed',
    memberSinceLabel: 'Member since',
    emailStatus: 'Email status',
    verified: 'Verified',
    notVerified: 'Not verified',
    notAvailable: 'Not available',
    messageOwner: 'Message owner',
    comingSoon: 'Coming soon',
    messagingNote:
      'In-app messaging is planned. Until then, use the available contact details to reach the owner.',
    myCarsCount: (n: number) => `My Cars (${n})`,
    myRentalsCount: (n: number) => `My Rentals (${n})`,
    backToProfile: 'Back to My Profile',
    accountSettingsTag: 'Account settings',
    editProfileHeroTitle: 'Make your profile feel like you.',
    editProfileHeroDesc:
      'Keep your photo and contact details current so owners and renters know who they are connecting with.',
    profilePhoto: 'Profile photo',
    publicIdentity: 'Your public identity',
    chooseNewPhoto: 'Choose new photo',
    photoFileHint: 'JPG, PNG or WebP. Maximum file size is 5 MB.',
    photoTrustHint:
      'A clear, recent photo helps build trust when arranging vehicle pickup and return.',
    personalDetails: 'Personal details',
    howPeopleReachYou: 'How people can reach you',
    fullName: 'Full Name',
    fullNamePlaceholder: 'e.g. Srdjan Markovic',
    phoneOrContact: 'Phone or Contact',
    phoneOrContactPlaceholder: 'e.g. +381 60 123 4567',
    emailLockedHint:
      'Email is used for sign-in and cannot be changed from this screen.',
  },

  drawer: {
    carDetails: 'Car Details',
    renter: 'Renter',
    noRenterInfo: 'No renter info available',
  },

  howItWorks: {
    modalTitle: 'How RentMyCar Works',
    browseMatch: 'Browse & Match',
    reserveInstantly: 'Reserve Instantly',
    smartHandover: 'Smart Handover',
    embarkSafely: 'Embark Safely',
    browseDesc:
      'Choose a city and travel dates, then narrow the results by price, make, body style, or engine type.',
    reserveDesc:
      'Open a listing to review the vehicle and daily price, then confirm your reservation for the selected dates.',
    handoverDesc:
      'Use the owner information provided with the listing to agree on the pickup location and handover details.',
    embarkDesc:
      'Keep your reservation details in your profile and contact the owner if the trip arrangements change.',
    gotIt: "Got It, Let's Ride",
  },

  navigation: {
    home: 'Home',
    signIn: 'Sign In',
    signInMobile: 'Sign-in',
    signUpMobile: 'Sign-up',
    profile: 'Profile',
    catalog: 'Catalog',
    howItWorksNav: 'How It Works',
    myProfileRentals: 'My Profile & Rentals',
  },

  landing: {
    premiumMarketplace: 'Premium Marketplace Network in Serbia',
    findBookCars: 'Find and Book Cars Across Serbia',
    fastEasyTrusted: 'Fast, Easy, Trusted',
    landingDesc:
      'Inspect vehicle specifications, calculate real-time day rates, and book from trusted local renters in Novi Sad and Belgrade.',
    premiumRides: 'Premium Rides',
    kilometersLogged: 'Kilometers Logged',
    verifiedHosts: 'Verified Hosts',
    rentMy: 'RentMy',
    carBrand: 'Car',
    copyright: 'Serbia Marketplace • © 2026',
    aboutUs: 'About Us',
    helpCenter: 'Help Center',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    verifiedVehicles: 'Verified Vehicles. Trusted Renters.',
    localCarMarketplace: 'Peer-to-peer car rental in Serbia',
    heroTitle: 'Your next car is closer than you think.',
    heroHighlight: 'Find it locally.',
    heroDescription:
      'Choose your city and travel dates, compare local cars, and reserve the one that fits your trip. Have a car? List it and put it to work.',
    jumpToSearch: 'Jump to car search',
    browseCars: 'Browse local cars',
    newToRentMyCar: 'New to RentMyCar?',
    howItWorksDescription:
      'See how searching, booking, and meeting the car owner works before you reserve.',
    findACar: 'Find a car',
    listYourCar: 'List your car',
    forCarOwners: 'For car owners',
    putYourCarToWork: 'Own a car? Put it to work.',
    ownerDescription:
      'Create a listing, set your daily price, and make your car available to local renters when it suits you.',
    addYourCar: 'Add your car',
    createListing: 'Create your listing',
    createListingDescription:
      'Add the vehicle details and photos renters need to see.',
    setYourPrice: 'Set your daily price',
    setYourPriceDescription:
      'Choose the daily rate that works for you and your car.',
    chooseAvailability: 'Receive reservations',
    chooseAvailabilityDescription:
      'Your car appears in searches for available rental dates.',
  },

  pages: {
    aboutHeading: 'About RentMyCar',
    aboutDesc1:
      'RentMyCar is a leading peer-to-peer car rental platform, connecting car renters with clients to create a seamless and affordable car rental experience.',
    aboutDesc2:
      'Founded in 2024, our mission is to revolutionize the car rental industry by providing a secure, flexible, and cost-effective alternative to traditional rental companies.',
    aboutDesc3:
      "We're committed to building a community of trust, where car renters can earn extra income and clients can find the perfect vehicle for their needs.",
    contactUs: 'Contact Us',
    sendMessage: 'Send Message',
    helpCenterHeading: 'Help Center',
    faqHeading: 'Frequently Asked Questions',
    faqQ1: 'How do I list my car?',
    faqA1:
      "To list your car, log in to your account and click on 'List a Car' in your dashboard. Follow the prompts to add details about your vehicle.",
    faqQ2: 'What if my car gets damaged?',
    faqA2:
      "All rentals include insurance coverage. If your car is damaged, report it immediately through our app or website, and we'll guide you through the claims process.",
    faqQ3: 'How do I get paid?',
    faqA3:
      'Payments are processed automatically after each completed rental. Funds are typically deposited into your linked bank account within 3-5 business days.',
    cantFind: "Can't find what you're looking for?",
    contactSupport: 'Contact our support team',
    termsHeading: 'Terms of Service',
    termsDesc:
      'Welcome to RentMyCar. By using our services, you agree to comply with and be bound by the following terms and conditions.',
    privacyHeading: 'Privacy Policy',
    privacyDesc1:
      'At RentMyCar, we are committed to protecting your privacy and ensuring the security of your personal information.',
    privacyDesc2:
      'We collect information you provide directly to us, such as when you create an account, list a car, or make a reservation.',
    privacyDesc3:
      'We use the information we collect to provide, maintain, and improve our services, as well as to communicate with you.',
    safetyFirst: 'Safety First',
    safetyCommitment: 'Our Commitment to Your Safety',
    safetyDesc:
      "At RentMyCar, your safety is our top priority. We've implemented several measures to ensure a secure experience for both car renters and clients.",
    safetyTips: 'Safety Tips',
    insurance: 'Comprehensive insurance coverage for every rental',
    backgroundChecks: 'Thorough background checks on all users',
    roadsideAssistance: '24/7 roadside assistance',
    securePayment: 'Secure payment processing',
    inAppMessaging: 'In-app messaging for safe communication',
    meetPublic: 'Always meet in a public place for car handovers',
    inspectVehicle:
      'Thoroughly inspect the vehicle before and after each rental',
    keepCommunication: 'Keep all communication within our platform',
    trustInstincts:
      'Trust your instincts - if something feels off, contact our support team',
    cancellationOptions: 'Cancellation Options',
    flexiblePolicy: 'Our Flexible Cancellation Policy',
    cancellationDesc:
      'We understand that plans can change. You can cancel your reservation at any time through your profile.',
    forClients: 'For Clients:',
    freeCancellationClient:
      'Free cancellation up to 24 hours before the rental start time',
    partialRefund: 'No automated refunds are processed through the app',
    noRefund: 'Contact the owner directly for any refund discussions',
    forRenters: 'For Car Renters:',
    freeCancellationRenter:
      'Free cancellation up to 48 hours before the rental start time',
    penaltyCancellation:
      "Cancellations made less than 48 hours before the rental start time may affect your listing's visibility",
    repeatedCancellations:
      "Repeated cancellations may affect your listing's visibility",
    howToCancel: 'How to Cancel a Reservation',
    stepLogin: 'Log in to your RentMyCar account',
    stepGoToReservations: 'Go to `My Reservations` in your dashboard',
    stepFindReservation: 'Find the reservation you want to cancel',
    stepClickCancel: 'Click on `Cancel Reservation` and follow the prompts',
    stepConfirmation:
      "You'll receive a confirmation email once the cancellation is processed",
    notFound: '404 Not Found',
    pageNotFound: 'Your visited page not found. You may go home page.',
    errorFallback: 'Something went wrong. Please try again later.',
    backToCatalog: 'Back to Catalog',
    ratingScale: ' / 5.0',
    acceptanceTerms: '1. Acceptance of Terms',
    userResponsibilities: '2. User Responsibilities',
    infoCollect: '1. Information We Collect',
    howWeUse: '2. How We Use Your Information',
    carImages: 'Car Images',
    clickToUploadPhotos: 'Click to upload photos',
    fileSelected: (n: number) => `${n} file selected`,
    filesSelected: (n: number) => `${n} files selected`,
    termsAdditional:
      'By accessing or using RentMyCar, you agree to these Terms of Service and our Privacy Policy.',
    userResponsibilitiesText:
      'Users are responsible for maintaining the confidentiality of their accounts and for all activities that occur under their accounts.',
  },

  carSpecs: {
    engine: 'Engine',
    power: 'Power',
    type: 'Type',
    citySpec: 'City',
    mileage: 'Mileage',
    consumption: 'Consumption',
    registration: 'Registration',
  },

  status: {
    available: 'Available',
    booked: 'Booked',
    inactive: 'Inactive',
    cancelled: 'Cancelled',
  },

  pushNotifications: {
    notSupported: 'Push notifications are not supported in this browser.',
    subscribed: 'You are subscribed to push notifications.',
    unsubscribe: 'Unsubscribe',
    enterNotificationMsg: 'Enter notification message',
    sendTest: 'Send Test',
    notSubscribed: 'You are not subscribed to push notifications.',
    subscribe: 'Subscribe',
    iosInstall: 'To install this app on your iOS device tap:',
    getAppStore: 'Get From App Store',
  },

  footer: {
    exclusive: 'Exclusive',
    subscribe: 'Subscribe',
    get10Off: 'Get 10% off your first order',
    enterYourEmail: 'Enter your email',
    support: 'Support',
    address: '111 Bijoy sarani, Dhaka, DH 1515, Bangladesh',
    email: 'exclusive@gmail.com',
    phone: '+88015-88888-9999',
    account: 'Account',
    myAccount: 'My Account',
    loginRegister: 'Login / Register',
    cart: 'Cart',
    wishlist: 'Wishlist',
    shop: 'Shop',
    quickLink: 'Quick Link',
    termsOfUse: 'Terms Of Use',
    faq: 'FAQ',
    contact: 'Contact',
    downloadApp: 'Download App',
    save3WithApp: 'Save $3 with App New User Only',
    copyrightRimel: '&copy; Copyright Rimel 2022. All right reserved',
  },

  sidebar: {
    sport: 'Sport',
    health: 'Health',
    education: 'Education',
    entertainment: 'Entertainment',
    addProvider: 'Add provider',
    manageMyAccount: 'Manage My Account',
  },

  validation: {
    emailRequired: 'Email is required',
    nameMinLength: 'First Name should be at least 3 characters long',
    invalidEmail: 'Invalid email address',
    passwordMinLength: 'Password should be at least 8 characters long',
    invalidPassword: 'Invalid password',
  },

  errors: {
    userDoesNotExist: 'User does not exist.',
    passwordResetSent: 'Password reset link has been sent to your email.',
    anErrorOccurred: 'An error occurred. Please try again.',
    userAlreadyExists: 'User already exists',
    imageTooLarge: 'Image too large after compression',
    errorProcessingImage: 'Error processing image',
    userCreated: 'User created successfully',
    signupError: 'An error occurred during signup',
    missingRequiredFields: 'Missing required fields',
    carNotFoundApi: 'Car not found',
    userNotFoundSession: 'User ID not found in session',
    bookingSuccessful: 'Booking successful',
    errorCreatingBooking: 'Error creating booking',
    missingDates: 'Missing required parameters (start and end dates)',
    searchError: 'An error occurred while searching for cars',
    invalidCarType: 'Invalid car type',
    invalidCarMake: 'Invalid car make',
    invalidEngineType: 'Invalid engine type',
    invalidCity: 'Invalid city',
    userIdRequired: 'User ID is required',
    internalServerError: 'Internal Server Error',
    emailRequiredApi: 'Email is required',
    userNotFound: 'User not found',
    errorFetchingUser: 'Error fetching user data',
    unauthorized: 'Unauthorized',
    missingCarId: 'Missing car ID',
    carDeleted: 'Car deleted successfully',
    errorDeletingCar: 'Failed to delete car',
    carUpdated: 'Car updated successfully',
    errorUpdatingCar: 'Failed to update car',
    titleRequired: 'Title is required',
    descriptionRequired: 'Description is required',
    addressRequired: 'Address is required',
    phoneNumberRequired: 'Phone Number is required',
    roleRequired: 'Role is required',
  },
};

export default l;
export type Language = typeof l;
