const l = {
  common: {
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save Changes',
    loading: 'Loading...',
    adding: 'Adding...',
    creating: 'Creating Account...',
    loggingIn: 'Logging In...',
    sending: 'Sending...',
    deleting: 'Deleting...',
    backToHome: 'Back to Home',
    backToLogin: 'Back to Log in',
    rememberedIt: 'Remembered it?',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    phoneNumber: 'Phone number',
    description: 'Description',
    signIn: 'Sign in',
    signUp: 'Sign up',
    getStarted: 'Get Started',
    logIn: 'Log in',
    logOut: 'Log out',
    signUpNow: 'Sign Up Now',
    signUpWithGoogle: 'Sign up with Google',
    search: 'Search',
    searchCars: 'Search Cars',
    loadMore: 'Load more',
    allCarsLoaded: 'All cars loaded',
    details: 'Details',
    specs: 'Specs',
    bookNow: 'Book Now',
    howItWorks: 'How it works',
    confirmReservation: 'Confirm Reservation',
    bookingFailed: 'Booking failed, please sign in to continue.',
    signInToReserve: 'Sign in to complete your reservation',
    noPhoto: 'No photo',
    pricePerDay: 'Price Per Day (€)',
    pickUp: 'Pick Up',
    returnDate: 'Return',
    estimatedTotal: 'Estimated Total',
    total: 'Total',
    unavailable: 'Unavailable',
    close: '✕',
    fileSelected: (n: number) => `${n} file selected`,
    filesSelected: (n: number) => `${n} files selected`,
    clickToUpload: 'Click to upload photos',
    days: (n: number) => `${n} day${n !== 1 ? 's' : ''}`,
    profileInitial: 'U',
    perDay: '/ day',
    andMore: (n: number) => `and ${n} more...`,
    saving: 'Saving...',
  },

  auth: {
    joinUs: 'Join Us',
    welcomeBack: 'Welcome Back',
    logInToRentMyCar: 'Log in to RentMyCar',
    createAnAccount: 'Create an Account',
    enterDetails: 'Enter your details to access your ride',
    startJourney: 'Start your journey with us today',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    forgotPassword: 'Forgot Password?',
    forgotPasswordHeading: 'Forgot your password?',
    forgotPasswordDesc: "Enter your email and we'll send you a reset link.",
    emailRequired: 'Email is required',
    enterEmail: 'Enter your email',
    sendResetLink: 'Send reset link',
    passwordResetSuccess:
      'Password reset link has been successfully sent to your email.',
    resetPasswordHeading: 'Reset your password',
    resetPasswordDesc: 'Enter and confirm your new password.',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordRequired: 'Password is required',
    confirmPasswordRequired: 'Please confirm your password',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordMaxLength: 'Password must be at most 128 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    invalidResetLink: 'This password reset link is invalid or missing.',
    resetPassword: 'Reset password',
    resettingPassword: 'Resetting password...',
    passwordResetComplete: 'Your password has been reset successfully.',
    somethingWrong: 'Something went wrong. Please try again.',
    createAccount: 'Create Account',
    errorOccurred: 'An error occurred. Please try again.',
    verifyEmailHeading: 'Verify your email',
    verificationSent:
      'We sent a verification link to your email. Please check your inbox and click the link to verify your account.',
    checkYourInbox:
      'Please check your inbox and click the verification link to verify your email address.',
    verificationSuccess: 'Your email has been verified successfully!',
    verificationFailed:
      'Verification failed. The link may be invalid or expired.',
    verifyButton: 'Verify Email',
    verifying: 'Verifying...',
    backToLogin: 'Back to Login',
    invalidCredentials: 'Invalid email or password',
    emailNotVerified: 'Please verify your email before logging in.',
  },

  cars: {
    addCar: 'Add Car',
    addNewCar: 'Add a New Car',
    addNewCarBtn: '+ Add New Car',
    myCars: 'My Cars',
    myRentals: 'My Rentals',
    addVehicleDesc: 'Add your vehicle details to create a rental listing',
    backToMyCars: 'Back to My Cars',
    secureListing: 'Secure listing setup',
    vehicleDetails: 'Vehicle details',
    vehicleDetailsDesc: 'Tell renters what makes your car the right choice.',
    rentalDetails: 'Location and pricing',
    rentalDetailsDesc: 'Set the pickup point and your daily rental price.',
    descriptionPlaceholder:
      'Describe the condition, features, and anything renters should know...',
    carImagesDesc: 'Add clear photos from several angles.',
    imageHint: 'JPG, PNG or WEBP',
    selectedPhotos: 'Selected photos',
    carImagePreview: 'Selected car preview',
    removeImage: 'Remove image',
    publishHint:
      'Review the details and publish your car when everything looks right.',
    publishCar: 'Publish Car',
    make: 'Make',
    model: 'Model',
    carType: 'Car Type',
    engineType: 'Engine Type',
    horsepower: 'Horsepower (HP)',
    horsepowerMobile: 'Horsepower',
    seats: 'Seats',
    avgConsumption: 'Avg. Consumption (L/100km)',
    mileage: 'Mileage (km)',
    city: 'City',
    selectCity: 'Select city',
    selectCityFirst: 'Select a city first',
    loadingAddressSuggestions: 'Loading address suggestions...',
    cityRequired: 'Please select a city.',
    carLocation: 'Car Location',
    firstRegistration: 'First Registration',
    selectDate: 'Select date',
    pricePerDayLabel: 'Price Per Day (€)',
    carImages: 'Car Images',
    updateCar: 'Update Car',
    editVehicleDesc: 'Edit your vehicle details',
    saveChanges: 'Save Changes',
    deleteCar: 'Delete Car',
    deleteCarConfirm:
      'Are you sure you want to delete this car? This action cannot be undone.',
    deleteCarError: 'Failed to delete car. Please try again.',
    updateCarError: 'Failed to update car',
    firstRegistrationRequired: 'First registration is required!',
    atLeastOneImage: 'At least one image is required!',
    failedAddCar: 'Failed to add car. Please try again.',
    eg: 'e.g.',
    egCClass: 'e.g. C-Class',
    eg150: 'e.g. 150',
    eg65L: 'e.g. 6.5',
    eg50000: 'e.g. 50000',
    egStreetLocation: 'Street location',
    eg45: 'e.g. 45',
    chooseFiles: 'Choose Files',
    carUnavailable: '🚗 Car unavailable',
  },

  search: {
    location: 'Location',
    allCities: 'All Cities (Serbia)',
    allCitiesMobile: 'All cities (Serbia)',
    pickUp: 'Pick Up',
    returnDate: 'Return',
    filters: 'Filters',
    priceRange: 'Price Range (per day)',
    priceRangeEur: 'Price Range (€/day)',
    priceRangePerDay: 'Price Range (per day)',
    min: 'Min',
    max: 'Max',
    minPlaceholder: 'Min',
    maxPlaceholder: 'Max',
    pickUpLabel: 'Pick Up',
    returnLabel: 'Return',
    carMake: 'Car Make',
    allMakes: 'All Makes',
    allManufacturers: 'All Manufacturers',
    carType: 'Car Type',
    allTypes: 'All Types',
    engineType: 'Engine Type',
    allEngineTypes: 'All Engine Types',
    minimumSeats: 'Minimum Seats',
    anyNumberOfSeats: 'Any number of seats',
    pricesDisclaimer:
      'Prices in Euros (€) and exclude customized dropoff charges.',
    availableCars: 'Available Cars',
    noCarsFound: 'No cars found...',
    findPerfectRide: 'Find Your Perfect Ride',
    findCompareChoose:
      'Find, compare, and choose the perfect car for your next trip.',
    bookingForDays: (n: number) => `Booking for ${n} days`,
    pickUpDate: 'Pick-up Date',
    returnDateLabel: 'Return Date',
    selectDatesFirst:
      'Select pick-up and return dates to search for available cars.',
    searchFailed: 'We could not load available cars. Please try again.',
    startSearchTitle: 'Choose your dates to start searching',
    startSearchDescription:
      'Available cars will appear here after you select your trip dates.',
    carsFound: (n: number) => `${n} ${n === 1 ? 'car' : 'cars'} available`,
    showFilters: 'Show filters',
    hideFilters: 'Hide filters',
    clearFilters: 'Clear filters',
    tryDifferentSearch: 'Try different dates, another city, or fewer filters.',
  },

  booking: {
    bookMakeModel: (make: string, model: string) => `Book ${make} ${model}`,
    bookingSuccessful: 'Booking successful',
    errorCreatingBooking: 'Error creating booking',
    unauthorized: 'Unauthorized',
    missingRequiredFields: 'Missing required fields',
    carNotFound: 'Car not found',
    userNotFoundSession: 'User ID not found in session',
    cancelReservation: 'Cancel Reservation',
    cancelReservationConfirm:
      'Are you sure you want to cancel this reservation? The car will become available again for these dates.',
    keepReservation: 'Keep Reservation',
    cancellingReservation: 'Cancelling...',
    reservationCancelled: 'Reservation cancelled successfully',
    reservationAlreadyCancelled: 'This reservation is already cancelled',
    cancellationCutoffPassed:
      'Cancellation is unavailable less than 24 hours before the rental starts',
    cannotCancelReservation:
      'You are not authorized to cancel this reservation',
  },

  profile: {
    editProfile: 'Edit Profile',
    editProfileBtn: 'Edit Profile',
    myCars: 'My Cars',
    myRentals: 'My Rentals',
    myCarsHeading: 'My Cars',
    myRentalsHeading: 'My Rentals',
    addNewCar: 'Add New Car',
    noCarsListed: "You haven't listed any cars yet.",
    noRentalsYet: "You haven't rented any cars yet.",
    memberSince: (date: string) => `Member since ${date}`,
    noPhoneNumber: 'No phone number added',
    cars: 'Cars',
    rentals: 'Rentals',
    rating: 'Rating',
    carOwner: 'Car owner',
    ownerProfile: 'Owner profile',
    ownerIntro: 'Meet the local owner behind the car you are considering.',
    contactOwner: 'Contact this owner',
    contactDescription:
      'Use the details below when you need to coordinate your rental directly with the owner.',
    emailAddress: 'Email address',
    phoneNumber: 'Phone number',
    member: 'Member',
    rentMyCarOwner: 'RentMyCar owner',
    noRatingYet: 'No ratings yet',
    viewOwnerProfile: 'View public profile',
    ownerAtGlance: 'Owner at a glance',
    carsListed: 'Cars listed',
    memberSinceLabel: 'Member since',
    emailStatus: 'Email status',
    verified: 'Verified',
    notVerified: 'Not verified',
    notAvailable: 'Not available',
    messageOwner: 'Message owner',
    comingSoon: 'Coming soon',
    messagingNote:
      'In-app messaging is planned. Until then, use the available contact details to reach the owner.',
    myCarsCount: (n: number) => `My Cars (${n})`,
    myRentalsCount: (n: number) => `My Rentals (${n})`,
    backToProfile: 'Back to My Profile',
    accountSettingsTag: 'Account settings',
    editProfileHeroTitle: 'Make your profile feel like you.',
    editProfileHeroDesc:
      'Keep your photo and contact details current so owners and renters know who they are connecting with.',
    profilePhoto: 'Profile photo',
    publicIdentity: 'Your public identity',
    chooseNewPhoto: 'Choose new photo',
    photoFileHint: 'JPG, PNG or WebP. Maximum file size is 5 MB.',
    photoTrustHint:
      'A clear, recent photo helps build trust when arranging vehicle pickup and return.',
    personalDetails: 'Personal details',
    howPeopleReachYou: 'How people can reach you',
    fullName: 'Full Name',
    fullNamePlaceholder: 'e.g. Srdjan Markovic',
    phoneNumberPlaceholder: 'e.g. +381 60 123 4567',
    emailLockedHint:
      'Email is used for sign-in and cannot be changed from this screen.',
  },

  drawer: {
    carDetails: 'Car Details',
    renter: 'Renter',
    noRenterInfo: 'No renter info available',
  },

  howItWorks: {
    modalTitle: 'How RentMyCar Works',
    browseMatch: 'Browse & Match',
    reserveInstantly: 'Reserve Instantly',
    smartHandover: 'Smart Handover',
    embarkSafely: 'Embark Safely',
    browseDesc:
      'Choose a city and travel dates, then narrow the results by price, make, body style, or engine type.',
    reserveDesc:
      'Open a listing to review the vehicle and daily price, then confirm your reservation for the selected dates.',
    handoverDesc:
      'Use the owner information provided with the listing to agree on the pickup location and handover details.',
    embarkDesc:
      'Keep your reservation details in your profile and contact the owner if the trip arrangements change.',
    gotIt: "Got It, Let's Ride",
  },

  navigation: {
    home: 'Home',
    explore: 'Explore',
    listCar: 'List a car',
    mobileNavigation: 'Mobile navigation',
    signIn: 'Sign In',
    signInMobile: 'Sign-in',
    signUpMobile: 'Sign-up',
    profile: 'Profile',
    catalog: 'Catalog',
    howItWorksNav: 'How It Works',
    myProfileRentals: 'My Profile & Rentals',
  },

  landing: {
    premiumMarketplace: 'Premium Marketplace Network in Serbia',
    findBookCars: 'Find and Book Cars Across Serbia',
    fastEasyTrusted: 'Fast, Easy, Trusted',
    landingDesc:
      'Inspect vehicle specifications, calculate real-time day rates, and book from trusted local renters in Novi Sad and Belgrade.',
    premiumRides: 'Premium Rides',
    kilometersLogged: 'Kilometers Logged',
    verifiedHosts: 'Verified Hosts',
    rentMy: 'RentMy',
    carBrand: 'Car',
    copyright: 'Serbia Marketplace • © 2026',
    aboutUs: 'About Us',
    helpCenter: 'Help Center',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    verifiedVehicles: 'Verified Vehicles. Trusted Renters.',
    localCarMarketplace: 'Peer-to-peer car rental in Serbia',
    heroTitle: 'Your next car is closer than you think.',
    heroHighlight: 'Find it locally.',
    heroDescription:
      'Choose your city and travel dates, compare local cars, and reserve the one that fits your trip. Have a car? List it and put it to work.',
    jumpToSearch: 'Jump to car search',
    browseCars: 'Browse local cars',
    newToRentMyCar: 'New to RentMyCar?',
    howItWorksDescription:
      'See how searching, booking, and meeting the car owner works before you reserve.',
    findACar: 'Find a car',
    listYourCar: 'List your car',
    forCarOwners: 'For car owners',
    putYourCarToWork: 'Own a car? Put it to work.',
    ownerDescription:
      'Create a listing, set your daily price, and make your car available to local renters when it suits you.',
    addYourCar: 'Add your car',
    createListing: 'Create your listing',
    createListingDescription:
      'Add the vehicle details and photos renters need to see.',
    setYourPrice: 'Set your daily price',
    setYourPriceDescription:
      'Choose the daily rate that works for you and your car.',
    chooseAvailability: 'Receive reservations',
    chooseAvailabilityDescription:
      'Your car appears in searches for available rental dates.',
  },

  pages: {
    cancellationOptions: 'Cancellation Options',
    flexiblePolicy: 'Our Flexible Cancellation Policy',
    cancellationDesc:
      'Clients can cancel through their profile until 24 hours before the rental starts.',
    forClients: 'For Clients:',
    freeCancellationClient:
      'Cancellation is available until 24 hours before the rental start time',
    partialRefund: 'No automated refunds are processed through the app',
    noRefund: 'Contact the owner directly for any refund discussions',
    forRenters: 'For Car Renters:',
    freeCancellationRenter:
      'Free cancellation up to 48 hours before the rental start time',
    penaltyCancellation:
      "Cancellations made less than 48 hours before the rental start time may affect your listing's visibility",
    repeatedCancellations:
      "Repeated cancellations may affect your listing's visibility",
    howToCancel: 'How to Cancel a Reservation',
    stepLogin: 'Log in to your RentMyCar account',
    stepGoToReservations: 'Go to `My Reservations` in your dashboard',
    stepFindReservation: 'Find the reservation you want to cancel',
    stepClickCancel: 'Click on `Cancel Reservation` and follow the prompts',
    stepConfirmation:
      "You'll receive a confirmation email once the cancellation is processed",
    notFound: '404 Not Found',
    pageNotFound: 'Your visited page not found. You may go home page.',
    errorFallback: 'Something went wrong. Please try again later.',
    backToCatalog: 'Back to Catalog',
    ratingScale: ' / 5.0',
    carImages: 'Car Images',
    clickToUploadPhotos: 'Click to upload photos',
    fileSelected: (n: number) => `${n} file selected`,
    filesSelected: (n: number) => `${n} files selected`,
  },

  informational: {
    common: {
      navigationLabel: 'Information pages',
    },
    about: {
      eyebrow: 'About the platform',
      title: 'Local car sharing, made simpler for Serbia.',
      description:
        'RentMyCar connects people looking for a car with local owners who want to make their vehicle available. The platform keeps discovery, reservations and rental history in one clear place.',
      localTitle: 'Built around local trips',
      localDescription:
        'Search by Serbian city and travel dates, then compare locally listed cars without going through a traditional rental fleet.',
      clearTitle: 'Clear booking details',
      clearDescription:
        'See the daily price, vehicle specifications, availability and complete rental period before confirming a reservation.',
      directTitle: 'People remain in control',
      directDescription:
        'Owners manage their own listings, while clients choose the car that suits their trip and coordinate the handover directly.',
      howEyebrow: 'A straightforward process',
      howTitle: 'From local search to handover',
      stepOne: {
        title: 'Choose a place and dates',
        description:
          'Enter where and when you need a car to see listings available for the full selected period.',
      },
      stepTwo: {
        title: 'Review and reserve',
        description:
          'Compare photos, specifications, location and total estimated price before sending the reservation.',
      },
      stepThree: {
        title: 'Coordinate directly',
        description:
          'After an active reservation, use the available contact details to agree on pickup, return and payment.',
      },
      ctaEyebrow: 'Ready when you are',
      ctaTitle: 'Find a car for your next trip.',
      ctaDescription:
        'Browse vehicles available from local owners and choose the dates that work for you.',
      ctaAction: 'Browse cars',
    },
    help: {
      eyebrow: 'Help centre',
      title: 'Practical answers before you book or list a car.',
      description:
        'Learn how the main RentMyCar flows work, what the platform records and what owners and clients arrange directly.',
      faqEyebrow: 'Common questions',
      faqTitle: 'Using RentMyCar',
      questions: [
        {
          question: 'How do I reserve a car?',
          answer:
            'Choose a city and rental dates, open a listing and confirm the reservation. Unavailable periods are excluded and the final availability is checked again when you book.',
        },
        {
          question: 'When can I contact the owner?',
          answer:
            'The owner’s contact details are available to you while you have an active reservation with that owner. They are hidden from other visitors.',
        },
        {
          question: 'How are payment and deposit handled?',
          answer:
            'RentMyCar currently does not process payments or deposits. The owner and client agree on payment, deposit and handover details directly before the trip.',
        },
        {
          question: 'Can I cancel a reservation?',
          answer:
            'A client can cancel from My Profile when at least 24 hours remain before the rental begins. Later changes must be discussed directly with the owner.',
        },
        {
          question: 'How do I list my car?',
          answer:
            'Sign in, choose List a car and provide accurate vehicle details, location, photos and a daily price. You can review your listings from My Profile.',
        },
        {
          question: 'What should we check at handover?',
          answer:
            'Confirm identities, licence and vehicle documents where appropriate, inspect the car together and agree on fuel, mileage, return condition and any deposit in advance.',
        },
      ],
      safetyTitle: 'Important before every handover',
      safetyDescription:
        'RentMyCar does not currently provide insurance, payment processing, roadside assistance or background checks. Each user is responsible for confirming legal driving requirements, insurance coverage and the condition of the vehicle before the rental starts.',
      nextTitle: 'Already have a reservation?',
      nextDescription:
        'Open My Profile to review dates, status, rental details and the actions currently available to you.',
      nextAction: 'View My Profile',
    },
    terms: {
      eyebrow: 'Platform rules',
      title: 'Terms for using RentMyCar.',
      description:
        'These terms explain the role of the platform and the basic responsibilities of owners and clients when arranging a peer-to-peer car rental in Serbia.',
      sections: [
        {
          title: 'The role of RentMyCar',
          description:
            'RentMyCar provides tools for publishing vehicle listings, searching availability and recording reservations. It does not own the listed vehicles and is not a party to payment, deposit, insurance or vehicle handover arrangements made directly between users.',
        },
        {
          title: 'Accounts and accurate information',
          description:
            'Users must provide accurate account information, protect their login details and use the platform lawfully. A person who intends to drive must be legally permitted to do so and must confirm any licence, age and insurance requirements before the trip.',
        },
        {
          title: 'Vehicle listings',
          description:
            'An owner must have the right to offer the vehicle and should keep its description, photos, location, price and availability accurate. Material defects, restrictions and conditions that could affect the rental should be disclosed before handover.',
        },
        {
          title: 'Reservations and cancellations',
          description:
            'A reservation records the selected vehicle, dates and estimated total. Clients may cancel through My Profile until 24 hours before the rental starts. RentMyCar does not automatically process refunds, so any payment-related outcome must be agreed directly between the users.',
        },
        {
          title: 'Handover and user responsibility',
          description:
            'The owner and client are responsible for confirming identity, driving eligibility, insurance, vehicle condition, keys, fuel, mileage, payment and return arrangements. Users should not proceed when information is incomplete or the vehicle appears unsafe or unlawful to operate.',
        },
        {
          title: 'Acceptable use and availability',
          description:
            'The platform must not be used for fraud, misleading listings, unlawful activity, harassment or attempts to access another user’s data. Features may be updated or temporarily unavailable, and records may be retained where needed for security, rental history and legal obligations.',
        },
      ],
      noteTitle: 'Serbian law still applies',
      noteDescription:
        'These platform rules do not remove rights or obligations that apply under the laws of the Republic of Serbia, and they do not replace a specific agreement between the vehicle owner and client.',
      lastUpdated: 'Last updated: 2 September 2026',
    },
    privacy: {
      eyebrow: 'Your data',
      title: 'Privacy explained in plain language.',
      description:
        'This policy describes what personal data RentMyCar uses, why it is needed and the choices available to users under the data protection framework of the Republic of Serbia.',
      sections: [
        {
          title: 'Information you provide',
          description:
            'This includes account details such as your name, email address, phone number and profile image; vehicle listing details and photos; and the dates, participants, status and price information connected with a reservation.',
        },
        {
          title: 'How the information is used',
          description:
            'Data is used to create and secure accounts, verify email addresses, display listings, check vehicle availability, create and manage reservations, show rental history, send service emails and prevent misuse of the platform.',
        },
        {
          title: 'When information is shared',
          description:
            'Public profiles and listings use limited public information. Contact details are shown to the profile owner and to a client with a relevant active reservation. Necessary data may also be processed by hosting, database, email and analytics providers that support the service, or when required by law.',
        },
        {
          title: 'Cookies and technical data',
          description:
            'Authentication cookies keep users signed in and help protect restricted pages. The hosting platform and browser may also generate technical request, device and performance information needed to operate, secure and improve the application.',
        },
        {
          title: 'Retention and security',
          description:
            'Information is kept while it is needed to provide the account and booking features, preserve legitimate rental history, resolve security issues or meet legal obligations. RentMyCar uses access controls and protected server-side checks, but no online system can guarantee absolute security.',
        },
        {
          title: 'Your choices',
          description:
            'You can update profile information through your account. Subject to applicable Serbian law, you may also request access, correction, deletion, restriction, portability or object to certain processing when the legal conditions for that right are met.',
        },
      ],
      rightsTitle: 'Privacy rights in Serbia',
      rightsDescription:
        'The Commissioner for Information of Public Importance and Personal Data Protection provides official guidance on personal data rights and how they may be exercised.',
      rightsAction: 'Read official guidance',
      lastUpdated: 'Last updated: 2 September 2026',
    },
  },

  carSpecs: {
    engine: 'Engine',
    power: 'Power',
    type: 'Type',
    citySpec: 'City',
    mileage: 'Mileage',
    consumption: 'Consumption',
    registration: 'Registration',
    seats: 'Seats',
  },

  carDetailsPage: {
    metadataNotFound: 'Car not found | RentMyCar',
    metadataTitle: (carName: string, city: string) =>
      `${carName} in ${city} | RentMyCar`,
    metadataDescription: (carName: string, city: string, pricePerDay: number) =>
      `Rent ${carName} in ${city} from €${pricePerDay} per day. View photos, specifications and availability.`,
    backToCatalog: 'Back to catalog',
    localCarListing: 'Local car listing',
    perDay: 'per day',
    vehicleOverview: 'Vehicle overview',
    everythingForTrip: 'Everything you need for the trip',
    vehicleType: 'Vehicle type',
    firstRegistration: 'First registration',
    aboutThisCar: 'About this car',
    description: 'Description',
    missingDescription:
      'The owner has not added a description yet. Review the vehicle specifications and contact the owner after booking for handover details.',
    pickupLocation: 'Pickup location',
    findTheCar: 'Find the car on the map',
    openInGoogleMaps: 'Open in Google Maps',
    mapTitle: (carName: string) => `${carName} pickup location`,
    mapUnavailable: 'Map preview is currently unavailable',
    mapUnavailableDescription:
      'You can still open this location directly in Google Maps.',
    handoverLocationNote:
      'Confirm the exact pickup point and handover details with the owner before your trip.',
    yourHost: 'Your host',
    meetOwner: 'Meet the car owner',
    carRating: 'Car rating',
    ratingCount: (count: number) =>
      `${count} ${count === 1 ? 'rating' : 'ratings'}`,
    rating: (rating: string) => `${rating} rating`,
    noRatings: 'No ratings yet',
    memberSince: (date: string) => `Member since ${date}`,
    viewOwnerProfile: 'View owner profile',
    ownerUnavailable: 'Owner information is currently unavailable.',
    reserveThisCar: 'Reserve this car',
    pickupDate: 'Pickup date',
    returnDate: 'Return date',
    selectPickup: 'Select pickup',
    selectReturn: 'Select return',
    priceEstimate: 'Price estimate',
    chooseDates: 'Choose dates',
    days: (days: number) => `${days} day${days === 1 ? '' : 's'}`,
    selectDatesError: 'Select pickup and return dates.',
    unavailablePeriodError:
      'Those dates include an unavailable day. Choose another period.',
    signInToReserve: 'Sign in to reserve this car.',
    bookingFailed: 'Booking failed. Please try again.',
    connectionError: 'Booking failed. Check your connection and try again.',
    bookingSuccessful: (carName: string) =>
      `${carName} is reserved. You can review the trip in My Rentals.`,
    goToSignIn: 'Go to sign in',
    viewMyRentals: 'View My Rentals',
    reserving: 'Reserving…',
    bookNow: 'Book Now',
    availabilityNote:
      'Unavailable dates are disabled. Availability is checked again before confirmation.',
    tripTerms: 'Trip terms',
    cancellationPolicy: 'Cancellation policy',
    flexibleCancellation: 'Flexible cancellation',
    cancellationSummary:
      'Cancel before the trip begins. Payment and deposit arrangements are handled directly with the owner.',
    viewCancellationPolicy: 'View cancellation policy',
    paymentOptions: 'Payment options',
    payInPerson: 'Pay in person',
    paymentSummary:
      'Pay the owner at pickup or return, as agreed. A refundable security deposit may be requested at handover.',
    distanceIncluded: 'Distance included',
    unlimitedDistance: 'Unlimited',
    distanceSummary:
      'RentMyCar applies no mileage limit to this listing. Confirm any special usage with the owner before pickup.',
    carNotFound: 'Car not found',
    carNotFoundDescription:
      'This listing may have been removed or the link is no longer valid.',
    browseAvailableCars: 'Browse available cars',
    photoGallery: (carName: string) => `${carName} photo gallery`,
    photoAlt: (carName: string, photoNumber: number) =>
      `${carName}, photo ${photoNumber}`,
    previousPhoto: 'Previous car photo',
    nextPhoto: 'Next car photo',
    showPhoto: (photoNumber: number) => `Show car photo ${photoNumber}`,
    reviewBeforeBooking: 'Review the vehicle before booking',
    closeDetails: 'Close car details',
    previousImage: 'Previous car image',
    nextImage: 'Next car image',
    showImage: (imageNumber: number) => `Show image ${imageNumber}`,
    availableForRent: 'Available for rent',
    listedBy: 'Listed by',
    viewFullDetails: 'View full details',
  },

  status: {
    all: 'All',
    available: 'Available',
    booked: 'Booked',
    upcoming: 'Upcoming',
    ongoing: 'Ongoing',
    completed: 'Completed',
    inactive: 'Inactive',
    cancelled: 'Cancelled',
  },

  pushNotifications: {
    notSupported: 'Push notifications are not supported in this browser.',
    subscribed: 'You are subscribed to push notifications.',
    unsubscribe: 'Unsubscribe',
    enterNotificationMsg: 'Enter notification message',
    sendTest: 'Send Test',
    notSubscribed: 'You are not subscribed to push notifications.',
    subscribe: 'Subscribe',
    iosInstall: 'To install this app on your iOS device tap:',
    getAppStore: 'Get From App Store',
  },

  sidebar: {
    sport: 'Sport',
    health: 'Health',
    education: 'Education',
    entertainment: 'Entertainment',
    addProvider: 'Add provider',
    manageMyAccount: 'Manage My Account',
  },

  validation: {
    emailRequired: 'Email is required',
    nameMinLength: 'First Name should be at least 3 characters long',
    invalidEmail: 'Invalid email address',
    passwordMinLength: 'Password should be at least 8 characters long',
    invalidPassword: 'Invalid password',
    phoneNumberRequired: 'Phone number is required',
    invalidPhoneNumber: 'Enter a valid phone number',
  },

  reviews: {
    rateTrip: 'Rate this trip',
    rateClient: 'Rate client',
    carAndOwnerRated: 'Car and owner rated',
    clientRated: 'Client rated',
    tripComplete: 'Trip completed',
    clientTitle: 'How was your rental?',
    ownerTitle: 'How was this client?',
    clientDescription:
      'Your ratings help other renters choose confidently and help owners improve.',
    ownerDescription:
      'Share a fair rating based on communication and care of your vehicle.',
    rateCar: 'Rate the car',
    rateOwner: 'Rate the owner',
    rateClientLabel: 'Rate the client',
    selectRating: 'Select a rating from 1 to 5 stars',
    submit: 'Submit rating',
    submitting: 'Submitting...',
    cancel: 'Not now',
    success: 'Thanks! Your rating has been saved.',
    genericError: 'We could not save your rating. Please try again.',
    ratings: 'ratings',
  },

  errors: {
    userDoesNotExist: 'User does not exist.',
    passwordResetSent: 'Password reset link has been sent to your email.',
    anErrorOccurred: 'An error occurred. Please try again.',
    userAlreadyExists: 'User already exists',
    imageTooLarge: 'Image too large after compression',
    errorProcessingImage: 'Error processing image',
    userCreated: 'User created successfully',
    signupError: 'An error occurred during signup',
    missingRequiredFields: 'Missing required fields',
    carNotFoundApi: 'Car not found',
    userNotFoundSession: 'User ID not found in session',
    bookingSuccessful: 'Booking successful',
    errorCreatingBooking: 'Error creating booking',
    missingDates: 'Missing required parameters (start and end dates)',
    searchError: 'An error occurred while searching for cars',
    invalidCarType: 'Invalid car type',
    invalidCarMake: 'Invalid car make',
    invalidEngineType: 'Invalid engine type',
    invalidCity: 'Invalid city',
    userIdRequired: 'User ID is required',
    internalServerError: 'Internal Server Error',
    emailRequiredApi: 'Email is required',
    userNotFound: 'User not found',
    errorFetchingUser: 'Error fetching user data',
    unauthorized: 'Unauthorized',
    missingCarId: 'Missing car ID',
    carDeleted: 'Car deleted successfully',
    errorDeletingCar: 'Failed to delete car',
    carUpdated: 'Car updated successfully',
    errorUpdatingCar: 'Failed to update car',
    titleRequired: 'Title is required',
    descriptionRequired: 'Description is required',
    addressRequired: 'Address is required',
    phoneNumberRequired: 'Phone Number is required',
    roleRequired: 'Role is required',
  },
};

export default l;
export type Language = typeof l;
